# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44c86f3a3cae2ef2bdfa62b7fb26ac823f5dec58ddb4cb3321a5d55da2620dc7a52373fc5de5923b35ab6286af8c852088d6ad29eacf78d497161a2b189759e9

test:
  secret_key_base: 16e573ca6fd5fc8346dbef552983bc2d0ff5390db09e75c62a823b804d86a72953d606f95ab541d2c84d662c65843cdf934edb0c51899e4c7e6ed17863f687de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
